name: Common
on:
  pull_request:
    branches:
      - main
jobs:
  check-pull-request:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout commit
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: "go.mod"

      - name: Install Go tools
        run: |
          go install golang.org/x/tools/cmd/goimports@latest
          go install github.com/fzipp/gocyclo/cmd/gocyclo@latest
          go install github.com/go-critic/go-critic/cmd/gocritic@latest

      - name: Run fmt
        run: go fmt ./...

      - name: Run vet
        run: go vet ./...

      - name: Run imports
        run: goimports -w .

      - name: Run mod tidy
        run: go mod tidy -v

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

      - name: Run cyclo
        run: gocyclo -over 15 .

      - name: Run critic
        run: gocritic check ./...

      - name: Run test
        run: go test -v ./...
