name: Common actions
run-name: General actions
on:
  push:
jobs:
  Check-Commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: "go.mod"
      - name: Install Go tools
        run: |
          go install golang.org/x/lint/golint@latest
      - name: Run vet
        run: go vet ./...
      - name: Run lint
        run: golint -set_exit_status ./...
