name: Check each push
run-name: ${{ github.actor }} pushed to ${{ github.ref_name }}
on:
  push:
jobs:
  Check-Commit:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: "go.mod"
      - name: Checkout commit
        uses: actions/checkout@v3
      - name: Run vet
        run: go vet ./...
      - name: Run lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
