name: Release
on:
  release:
    types:
      - published

jobs:
  releases-matrix:
    name: Release binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1.32
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: "go.mod"
          project_path: "."
          binary_name: "awss"
          extra_files: LICENSE README.md
